SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `businessUser`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `businessUser` (
  `userID_business` INT NOT NULL,
  `totalRevenue` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`userID_business`),
  CONSTRAINT `userID_business` FOREIGN KEY (`userID_business`) REFERENCES `user` (`userID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `businessUser`
--

LOCK TABLES `businessUser` WRITE;
/*!40000 ALTER TABLE `businessUser` DISABLE KEYS */;
INSERT INTO `businessUser` VALUES (123,438414),(321,3459431),(223,45693),(221,0),(145,546954);
SET FOREIGN_KEY_CHECKS=1;
/*!40000 ALTER TABLE `businessUser` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2022-07-27 15:14:53

SET FOREIGN_KEY_CHECKS=1;